# Generated by Django 4.2.14 on 2024-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stop_alter_route_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
