# Generated by Django 4.2.14 on 2024-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stop_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='info',
            field=models.TextField(blank=True, default='Гагра'),
            preserve_default=False,
        ),
    ]
