# Generated by Django 4.2.14 on 2024-07-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stop_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route_stop')),
            ],
        ),
    ]
