# Generated by Django 4.2.14 on 2024-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_route_stop_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_stop',
            name='ordinal_number',
            field=models.IntegerField(default=0),
        ),
    ]
